export const TASK_STATUS_UPDATED = 'TASK_STATUS_UPDATED'
export const TASKS_TODAY_LOADED = 'tasks/today/loaded'
export const DASHBOARD_LOADED = 'dashboard/loaded'
export const CREATE_TASK= 'tasks/create'
export const DELETE_TASK= 'tasks/delete'
export const TASKS_LOADED = 'tasks/loaded'
export const TASKS_CHANGE_VISIBLE = 'tasks/changVisible'
